list:
  @just --list

_packages:
    brew install bat
    brew install bash
    brew install eza
    brew install fastfetch
    brew install fd
    brew install fzf
    brew install git
    brew install just
    brew install lazygit
    brew install neovim
    brew install ripgrep
    brew install sd
    brew install starship
    brew install tldr
    brew install yadm
    brew install yazi
    brew install imagemagick
    brew install ffmpegthumbnailer
    brew install zoxide
    brew install zsh

    brew install firefox --cask
    brew install font-jetbrains-mono-nerd-font --cask
    brew install font-droid-sans-mono-nerd-font --cask
    brew install font-fira-code-nerd-font --cask
    brew install google-chrome --cask
    brew install spotify --cask
    brew install transmission --cask
    brew install vlc --cask
    brew install wezterm --cask

[macos]
packages: _packages
    brew install aerospace --cask
    brew install balenaetcher --cask
    brew install keepingyouawake --cask

_homebrew:
    eval "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

[macos]
homebrew: _homebrew

[linux]
homebrew-redhat: _homebrew
    sudo yum groupinstall 'Development Tools'
    sudo yum install procps-ng curl file git
    sudo yum install libxcrypt-compat # needed by Fedora 30 and up

[linux]
homebrew-debian: _homebrew
    sudo apt-get install build-essential procps curl file git

dotfiles:
    yadm clone git@github.com:jeffwindsor/dotfiles.git
    yadm status

repos:
    mkdir -p $HOME/Source/github.com/
    git clone git@github.com:jeffwindsor/startpage.git $HOME/Source/github.com/jeffwindsor/startpage
    git clone git@github.com:jeffwindsor/financials-home.git $HOME/Source/github.com/jeffwindsor/financials-home
    git clone git@github.com:jeffwindsor/financials-wfp.git $HOME/Source/github.com/jeffwindsor/financials-wfp

_ssh-keys:
    sh-keygen -t ed25519 -f $HOME/.ssh/github.com -C "jeff.windsor@gmail.com"

[linux]
ssh-keys: _ssh-keys

[macos]
ssh-keys: _ssh-keys
    eval "$(ssh-agent -s)"
    ssh-add ~/.ssh/github.com

flatpacks:
    flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
  
