return {
  {
    "nvimdev/dashboard-nvim",
    opts = function(_, opts)
      opts.config.header = {
        "",
        "",
        "          ░░░░░░░░          ",
        "      ░░░░░░░░░░░░░░░░      ",
        "    ░░░░░░░░░░░░░░░░░░░░    ",
        "  ░░░░░░    ░░░░░░░░    ░░  ",
        "  ░░░░        ░░░░          ",
        "  ░░░░    ▒▒▒▒░░░░    ▒▒▒▒  ",
        "░░░░░░    ▒▒▒▒░░░░    ▒▒▒▒░░",
        "░░░░░░░░    ░░░░░░░░    ░░░░",
        "░░░░░░░░░░░░░░░░░░░░░░░░░░░░",
        "░░░░░░░░░░░░░░░░░░░░░░░░░░░░",
        "░░░░░░░░░░░░░░░░░░░░░░░░░░░░",
        "░░░░  ░░░░░░    ░░░░░░  ░░░░",
        "░░      ░░░░    ░░░░      ░░",
        "",
        "",
        "neovim",
        "",
      }
    end,
  },
}

-- '"=^)',
-- "",
-- "MOTTAINI ❀ waste nothing",
-- "ZAZEN ☸ sitting meditation",
-- "OUBAITORY ❀ do not compare yourself to others",
-- "IKIGAI ☸ a reason for being, a sense of purpose",
-- "SHIKATA GA NAI ❀ let go of what you cannot change",
-- "SHU-HA-RI ☸ three stage to aquiring true knowledge",
-- "KAIZEN ❀ always seek to improve all areas of your life",
-- "WABI SABI ☸ acceptance and appreciation for imperfection",
-- "GAMAN ❀ enduring the seemingly unbearable, with patience and dignity",
-- "MONO NO AWARE ☸ awareness of the impermanent/transient nature of things",
