#!/bin/bash
###############################################################################
# PACKAGES
#   maybe: just, nushell, shellcheck, xh
#   maybe: balenaetcher
###############################################################################
BREW_PACKAGES=(
  bat
  bash
  eza
  fastfetch
  fd
  fortune
  fzf
  git
  gum
  helix
  lazygit
  neovim
  ripgrep
  zoxide
  zsh
)

BREW_CASKS=(
  aerospace
  firefox
  font-jetbrains-mono-nerd-font
  google-chrome
  keepingyouawake
  spotify
  transmission
  vlc
  wezterm
  xbar
)

###############################################################################
# Functions
###############################################################################
function echo_header() {
  echo -ne "\e[38;5;39m ===> ${1} \e[0m"
}

###############################################################################
# INSTALL SCRIPT
###############################################################################
cd "$(dirname "${0}")" || exit
clear

if command -v brew &>/dev/null; then

  echo_header "brew leaves"
  brew leaves

  echo "brew casks"
  brew list --cask

else

  echo_header "installing brew"
  eval "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

  echo_header "installing brew packages"
  for i in "${BREW_PACKAGES[@]}"; do
    echo_header "installing $i"
    brew install "$i"
  done

  echo_header "installing brew casks"
  for i in "${BREW_CASKS[@]}"; do
    echo_header "installing $i"
    brew install "$i" --cask
  done

fi
