#!/bin/bash

###############################################################################
# PACKAGES
###############################################################################
BREW_PACKAGES=(
	bat
	eza
	fd
	fzf
	git
	helix
	just
	lazygit
	neovim
	nushell
	podman
	ripgrep
	shellcheck
	starship
	tldr
	xh
	yadm
	yazi
	zoxide
	zsh-autocomplete
	zsh-completions
	zsh-syntax-highlighting
)

BREW_CASKS=(
	amethyst
	firefox
	font-jetbrains-mono-nerd-font
	google-chrome
	keepingyouawake
	podman-desktop
	slack
	spaceid
	spotify
	transmission
	vlc
	wezterm
)

###############################################################################
# Functions
###############################################################################
function echo_header() {
	echo -ne "\e[38;5;39m ===> ${1} \e[0m"
}

###############################################################################
# INSTALL SCRIPT
###############################################################################
cd "$(dirname "${0}")" || exit
clear

echo -ne "\e[38;5;39m
██████╗  █████╗ ██████╗ ██╗    ██╗██╗███╗   ██╗
██╔══██╗██╔══██╗██╔══██╗██║    ██║██║████╗  ██║
██║  ██║███████║██████╔╝██║ █╗ ██║██║██╔██╗ ██║
██║  ██║██╔══██║██╔══██╗██║███╗██║██║██║╚██╗██║
██████╔╝██║  ██║██║  ██║╚███╔███╔╝██║██║ ╚████║
╚═════╝ ╚═╝  ╚═╝╚═╝  ╚═╝ ╚══╝╚══╝ ╚═╝╚═╝  ╚═══╝
\e[0m
"

# package manager: https://brew.sh/
if command -v brew &>/dev/null; then

	echo_header "brew leaves"
	brew leaves

	echo "brew casks"
	brew list --cask

else

	echo_header "installing brew"
	eval $(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)

	echo_header "installing brew packages"
	for i in "${BREW_PACKAGES[@]}"; do
		echo_header "installing $i"
		brew install "$i"
	done

	echo_header "installing brew casks"
	for i in "${BREW_CASKS[@]}"; do
		echo_header "installing $i"
		brew install "$i" --cask
	done

fi

# ssh keys and repos from github
if ! test -f $HOME/.ssh/github.com.pub; then

	ssh-keygen -t ed25519 -C "jeff.windsor@gmail.com" -f $HOME/.ssh/github.com
	eval "$(ssh-agent -s)"
	ssh-add ~/.ssh/github.com

	echo_header "add ssh public key to github"
	cat $HOME/.ssh/*.pub
	echo "hit any key when completed"
	read -r

	echo_header "cloning personal github repos"
	JEFF="$HOME/Source/github.com/jeffwindsor"
	git clone git@github.com:jeffwindsor/startpage.git "$JEFF"/startpage

	read -r -p "Personal Repos? [y/N]" -n 1
	if [[ "$REPLY" =~ ^[Yy]$ ]]; then
		git clone git@github.com:jeffwindsor/financials-home.git "$JEFF"/financials-home.git
		git clone git@github.com:jeffwindsor/financials-wfp.git "$JEFF"/financials-wfp.git
	fi

fi

# dotfiles : https://yadm.io/
if command -v yadm &>/dev/null; then

	echo_header "configuring dot files (yadm)"
	yadm clone git@github.com:jeffwindsor/dotfiles.git
	yadm status

fi
