#!/bin/bash
###############################################################################
# PACKAGES
#   maybe: just, nushell, shellcheck, xh
#   maybe: balenaetcher
###############################################################################
BREW_PACKAGES=(
  bat
  bash
  eza
  fastfetch
  fd
  fzf
  git
  just
  lazygit
  neovim
  ripgrep
  sd
  starship
  tldr
  yadm
  yazi
  zoxide
  zsh
)

BREW_CASKS=(
  aerospace
  balenaetcher
  firefox
  font-jetbrains-mono-nerd-font
  font-droid-sans-mono-nerd-font
  font-fira-code-nerd-font
  google-chrome
  keepingyouawake
  spotify
  transmission
  vlc
  wezterm
)

###############################################################################
# Functions
###############################################################################
function echo_header() {
  echo -ne "\e[38;5;39m ===> ${1} \e[0m"
}

###############################################################################
# INSTALL SCRIPT
###############################################################################
cd "$(dirname "${0}")" || exit
clear

echo_header "installing brew packages"
for i in "${BREW_PACKAGES[@]}"; do
  echo_header "installing $i"
  brew install "$i"
done

echo_header "installing brew casks"
for i in "${BREW_CASKS[@]}"; do
  echo_header "installing $i"
  brew install "$i" --cask
done
